import Head from 'next/head'
import Image from 'next/image'

import Banner from '../components/banner/Banner'
import Card from '../components/card/card'
import NavBar from '../components/nav/navbar'
import Cardwrap from '../components/cardwrap/Cardwrap';

import styles from '../styles/Home.module.css'

export default function Home() {
 const videos = [
   {imgUrl: '/static/wanda.jpg'},{imgUrl: '/static/wanda.jpg'},{imgUrl: '/static/wanda.jpg'},
   {imgUrl: '/static/wanda.jpg'},{imgUrl: '/static/wanda.jpg'},{imgUrl: '/static/wanda.jpg'},
   {imgUrl: '/static/wanda.jpg'},{imgUrl: '/static/wanda.jpg'},{imgUrl: '/static/wanda.jpg'},
   {imgUrl: '/static/wanda.jpg'},{imgUrl: '/static/wanda.jpg'},{imgUrl: '/static/wanda.jpg'},
   {imgUrl: '/static/wanda.jpg'},{imgUrl: '/static/wanda.jpg'},{imgUrl: '/static/wanda.jpg'},
 ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
        <h1 className={styles.title}>
          NextFlix
        </h1>

        <Banner 
           title="Loki "
           subTitle="The god of mischief returns"
            imgUrl="./static/lok.jpg"/>

         <NavBar 
           username ="Alex"
          />

          <div className={styles.sectionWrapper}>
            <Cardwrap title="Disney + "  videos={videos} size="large"/>

            <Cardwrap title="Productivity"  videos={videos} size="medium"/>
          </div>

         <Card 
            imgUrl='/static/mobius.jpg'
            size='large'
          /> 

          

          <Card 
            size='small'
          /> 
    </div>
  )
}
