import Head from 'next/head'
import Image from 'next/image'

import Banner from '../components/banner/Banner'
import Card from '../components/card/card'
import NavBar from '../components/nav/navbar'


import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
        <h1 className={styles.title}>
          NextFlix
        </h1>

        <Banner 
           title="Loki "
           subTitle="The god of mischief returns"
            imgUrl="./static/lok.jpg"/>

         <NavBar 
           username ="Alex"
          />

         <Card 
            imgUrl='/static/mobius.jpg'
            size='large'
          /> 

          <Card 
            imgUrl='/static/mobius.jpg'
            size='medium'
          /> 

          <Card 
            size='small'
          /> 
    </div>
  )
}
